[AlsaMidi]
Enabled=true

[FilterNodes]
Enabled=false
List=@Invalid()

[GraphCanvas]
CanvasRect=@Variant(\0\0\0\x14\xc0\x92p\xb8Q\xeb\x85\x1f\xc0\x85\t\\(\xf5\xc2\x90@\xa4\xb9\xb0Q\xeb\x85\x1f@\x94M\\(\xf5\xc2\x90)
CanvasZoom=1

[GraphColors]
0x172973e6=#006b6b
0x2c2fdc12=#6b006b
0x30fc78a9=#6b0000
0x50c34e7e=#6b6b00
0xb91441cf=#006b00

[GraphGeometry]
qpwgraph_main=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\ag\0\0\x4\x1\0\0\0\0\0\0\0\0\0\0\ag\0\0\x4\x1\0\0\0\0\x2\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\ag\0\0\x4\x1)

[GraphLayout]
qpwgraph_main=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\ah\0\0\x3\x83\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\x2\0\0\0\x2\0\0\0\x1\0\0\0\x18\0g\0r\0\x61\0p\0h\0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\x2\0\0\0\x1\0\0\0\x1e\0p\0\x61\0t\0\x63\0h\0\x62\0\x61\0y\0T\0o\0o\0l\0\x62\0\x61\0r\x1\0\0\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0)

[GraphNodePos]
14%3AMidi%20Through%3AInput=@Variant(\0\0\0\x1a\xc0r\xc0\0\0\0\0\0@\x10\0\0\0\0\0\0)
14%3AMidi%20Through%3AOutput=@Variant(\0\0\0\x1a\xc0\x80\xa0\0\0\0\0\0\xc0k\x80\0\0\0\0\0)
BLE%20MIDI%201%3AInput=@Variant(\0\0\0\x1a\xc0\x80 \0\0\0\0\0@0\0\0\0\0\0\0)
BLE%20MIDI%201%3AOutput=@Variant(\0\0\0\x1a\xc0\x80\xe0\0\0\0\0\0\xc0]\0\0\0\0\0\0)
Built-in%20Audio%20Analog%20Stereo%20%5BMonitor%5D=@Variant(\0\0\0\x1a@n\0\0\0\0\0\0\xc0n\x80\0\0\0\0\0)
Built-in%20Audio%20Analog%20Stereo%3AInput=@Variant(\0\0\0\x1a@k\0\0\0\0\0\0\xc0w@\0\0\0\0\0)
Built-in%20Audio%20Analog%20Stereo%3AOutput=@Variant(\0\0\0\x1a\xc0q\xc0\0\0\0\0\0\xc0w\x80\0\0\0\0\0)
Integrated%20Camera%20%28V4L2%29%3AOutput=@Variant(\0\0\0\x1a\xc0\x80\xa0\0\0\0\0\0\xc0s\x80\0\0\0\0\0)
Midi-Bridge%3AInput=@Variant(\0\0\0\x1a\xc0v\xc0\0\0\0\0\0@`\x80\0\0\0\0\0)
Midi-Bridge%3AOutput=@Variant(\0\0\0\x1a\xc0t@\0\0\0\0\0\xc0\\\0\0\0\0\0\0)
PulseAudio%20Volume%20Control=@Variant(\0\0\0\x1a@p\0\0\0\0\0\0\0\0\0\0\0\0\0\0)
PulseAudio%20Volume%20Control-1=@Variant(\0\0\0\x1a@p\0\0\0\0\0\0\xc0_\0\0\0\0\0\0)
PulseAudio%20Volume%20Control-2=@Variant(\0\0\0\x1a@o\0\0\0\0\0\0\xc0\x38\0\0\0\0\0\0)
PulseAudio%20Volume%20Control-2_1=@Variant(\0\0\0\x1a@o\0\0\0\0\0\0\xc0\x38\0\0\0\0\0\0)
Zen%3AOutput=@Variant(\0\0\0\x1a\xc0q\xc0\0\0\0\0\0\xc0p\xc0\0\0\0\0\0)
Zen_1%3AOutput=@Variant(\0\0\0\x1a\xc0p\xc0\0\0\0\0\0\xc0p@\0\0\0\0\0)
cava=@Variant(\0\0\0\x1a@\x86 \0\0\0\0\0\xc0q@\0\0\0\0\0)
vis=@Variant(\0\0\0\x1a@\x85\xa0\0\0\0\0\0\xc0\x61\x80\0\0\0\0\0)

[GraphView]
ConnectThroughNodes=false
Menubar=true
RepelOverlappingNodes=false
SortOrder=0
SortType=0
Statusbar=true
TextBesideIcons=true
Thumbview=0
Toolbar=true
ZoomRange=false

[MergerNodes]
Enabled=false
List=@Invalid()

[Patchbay]
Activated=false
AutoDisconnect=false
AutoPin=true
Dir=
Exclusive=false
Path=
QueryQuit=true
RecentFiles=@Invalid()
Toolbar=true

[SystemTray]
Enabled=true
QueryClose=true
StartMinimized=false
