[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\xf/home/nightmare)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x4Z\0\0\x2\x32\0\0\as\0\0\x4+\0\0\x4Z\0\0\x2\x32\0\0\as\0\0\x4+\0\0\0\0\0\0\0\0\a\x80\0\0\x4Z\0\0\x2\x32\0\0\as\0\0\x4+)

[Epanel]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x1\xc2\0\0\0\0\0\0\x3\x8f\0\0\x1\xc0\0\0\x1\xc2\0\0\0\0\0\0\x3\x8f\0\0\x1\xc0\0\0\0\0\0\0\0\0\a\x80\0\0\x1\xc2\0\0\0\0\0\0\x3\x8f\0\0\x1\xc0)

[FullScreen]
pos=@Point(0 0)
screen=@Rect(0 0 0 0)
wide=false

[MainWindow]
QtStyle=System's default
adv-controls=0
bgSize=@Size(600 0)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Preferences]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xe1\0\0\0\xb6\0\0\a\0\0\0\x3q\0\0\x3\xe1\0\0\0\xb6\0\0\a\0\0\0\x3q\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xe1\0\0\0\xb6\0\0\a\0\0\0\x3q)

[RecentsMRL]
list=file:///run/media/nightmare/2004-1014/DCIM/DCIMA/MOVA3840.avi, file:///run/media/nightmare/2004-1014/DCIM/DCIMA/MOVA3824.avi, file:///run/media/nightmare/2004-1014/DCIM/DCIMA/MOVA3842.avi, file:///run/media/nightmare/2004-1014/DCIM/DCIMB/MOVB3860.avi, file:///home/nightmare/MOVA3824.avi, file:///run/media/nightmare/2004-1014/DCIM/DCIMB/MOVB3823.avi, file:///home/nightmare/Downloads/linuxmint-22.2-cinnamon-64bit.iso
times=0, 0, 8900, 0, 0, 0, 0
